FROM node:22-alpine

WORKDIR /app

COPY package*.json ./
COPY apps/api/package.json apps/api/package.json
COPY apps/worker/package.json apps/worker/package.json
COPY apps/web/package.json apps/web/package.json
COPY packages/prisma/package.json packages/prisma/package.json
COPY packages/email/package.json packages/email/package.json
RUN npm ci

COPY . .
RUN npm run db:generate -w @dipantauin/prisma

EXPOSE 3001
CMD ["npm", "run", "dev", "-w", "@dipantauin/api"]
